name: Python CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run lint (pylint)
      run: |
        pylint simple_math.py test_simple_math.py

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Build Docker image
      run: |
        docker build -t pipeline-ci-cd .

